export const GET_BALANCE = 'GET_BALANCE';

export const LOGIN = 'LOGIN';
export const GET_DEPOSITE_LP = 'GET_DEPOSITE_LP';
export const EARN_SUCCESS = 'EARN_SUCCESS';
export const SHOW_REWARD = 'SHOW_REWARD';
export const BNB_BALANCE = 'BNB_BALANCE';
export const WALLET_BALANCE = 'WALLET_BALANCE';
export const ERROR = 'ERROR';
export const CLEAR_ERROR_SUCCESS = 'CLEAR_ERROR_SUCCESS';

export const LP_PER_WSB = 'LP_PER_WSB';
export const WSB_PER_LP = 'WSB_PER_LP';
export const TOKEN_BALANCE = 'TOKEN_BALANCE';
export const CHECK_WALLET_CONNECT = 'CHECK_WALLET_CONNECT';

export const WALLET_CONNECT_CHECK = 'WALLET_CONNECT_CHECK';
export const SET_TOLERANCE = 'SET_TOLERANCE';
export const SET_DEADLINE = 'SET_DEADLINE';
export const START = 'START';
export const STOP = 'STOP';
export const SUCCESS = 'SUCCESS';
export const SET_CHAINID = 'SET_CHAINID';
export const DISABLED_CHAINID = 'DISABLED_CHAINID';
export const HASH = 'HASH';
export const NOTIFICATION_OPEN = 'NOTIFICATION_OPEN';
export const NOTIFICATION_CLOSE = 'NOTIFICATION_CLOSE';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const PENDING = 'PENDING'; 
export const CLEAR_TRANSACTION = 'CLEAR_TRANSACTION';